### ISSUE TITLE
Strange Gaps and Resultant Seams

### ISSUE THREAD

**Issue by tuncof** [TheLongRunSmoke/g1tog23#3]
Hi ya,

To evaluate smoothness of transition between circular and linear regions properly, I did write a simple openscad script like that:

$fn=80;
r=20;
d=10;
module k(){translate([-d,0,0])cylinder(h=10,r=r,center=true);}
rotate([0,0,0])union(){
k();mirror()k();
cube([2\*d,2\*r,10],center=true);}

Nothing fancy there, just two distanced halves of a cylinder with a height of 10mm and a radius of 20mm, halves are seperated with a distance of 20mm, which is filled with a box with the same height with cylinders. So a simple finger biscuit or a bacteria-like shape. Exporting as a stl file, sliced with Cura 4.4 and then processed with g1tog23.py with default settings. Upon investigating gcode in Repetier-Host, there were gaps between circular and linear transition regions. Apparently, these occured to me the culpirit of seams after printing, if I'm not mistaken. Tried every other option of g1tog23.py and even increased segment number from 80 all the way up to 200 ($fn in openscad) to no avail. Strange to me that some regions are perfectly smooth while others are bulgingly seamed. Attached are the unpeocessed and processed gcodes. Any ideas?  TIA.

STL file and GCODES after cura and g1tog23.py:
[cubecylinder.zip](https://github.com/FormerLurker/ArcWelderLib/files/6663056/cubecylinder.zip)

##
Repetier-Host preview after Cura:
<img width="499" alt="cura" src="https://user-images.githubusercontent.com/75937212/122213365-8ae92300-ceb1-11eb-931d-a69b32dd81a7.PNG">

After Processing with g1tog23.py (Greens are perfectly smooth while reds are aberrant after printing):
<img width="417" alt="arcweld" src="https://user-images.githubusercontent.com/75937212/122213565-c388fc80-ceb1-11eb-9938-4bdd34a06915.PNG">

Seams Look Like:
<img width="417" alt="blob1" src="https://user-images.githubusercontent.com/75937212/122216909-92aac680-ceb5-11eb-9e93-72d0b0476519.png">
<img width="417" alt="blob1" src="https://user-images.githubusercontent.com/75937212/122217272-eddcb900-ceb5-11eb-9de4-e85fcc4acb4e.png">

**Comment by TheLongRunSmoke** [comment]
Thank you for detailed report. Another side turn out smooth, right? Cura generate strange travels here.
![image](https://user-images.githubusercontent.com/5612507/122511230-5778d680-d020-11eb-96ef-0b4381aa2847.png)
In any case you found details for #2.

[ArcWelder](https://github.com/FormerLurker/ArcWelderLib) work slightly different. Try gcode processed by  this script.
[cubecylinder_after_g1tog23.zip](https://github.com/TheLongRunSmoke/g1tog23/files/6674778/cubecylinder_after_g1tog23.zip)
